import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

/**
 * Map of icon names to their Iconify collection and ID
 * Format: { displayName: { collection: 'ri', id: 'instagram-line' } }
 */
const iconMap = {
  instagram: { collection: 'ri', id: 'instagram-line' },
  linkedin: { collection: 'jam', id: 'linkedin-circle' },
  github: { collection: 'iconoir', id: 'github-circle' },
  bluesky: { collection: 'ri', id: 'bluesky-line' },
  telegram: { collection: 'iconoir', id: 'telegram-circle' },
  blog: { collection: 'ph', id: 'bookmark-simple-bold' },
  cv: { collection: 'tabler', id: 'file-cv' },
  phone: { collection: 'iconoir', id: 'phone' },
  whatsapp: { collection: 'ri', id: 'whatsapp-line' },
  line: { collection: 'streamline-logos', id: 'line-app-logo' },
  signal: { collection: 'arcticons', id: 'signal' },
};

/**
 * Load an icon SVG from @iconify/json
 * @param {string} collection - Icon collection name (e.g., 'ri', 'jam')
 * @param {string} id - Icon ID (e.g., 'instagram-line')
 * @returns {string | null} SVG string or null if not found
 */
function loadIconSvg(collection, id) {
  try {
    // Load the collection data from @iconify/json
    const collectionPath = join(
      __dirname,
      '..',
      'node_modules',
      '@iconify',
      'json',
      'json',
      `${collection}.json`,
    );

    if (!existsSync(collectionPath)) {
      console.warn(`Collection ${collection} not found at ${collectionPath}`);
      return null;
    }

    const collectionData = JSON.parse(readFileSync(collectionPath, 'utf-8'));
    const iconData = collectionData.icons[id];

    if (!iconData) {
      console.warn(`Icon ${id} not found in collection ${collection}`);
      return null;
    }

    // Build the SVG from the icon data
    const width = iconData.width || collectionData.width || 24;
    const height = iconData.height || collectionData.height || 24;
    const body = iconData.body || '';

    return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" width="1em" height="1em" fill="currentColor">${body}</svg>`;
  } catch (err) {
    console.warn(`Error loading icon ${collection}/${id}:`, err.message);
    return null;
  }
}

/**
 * Load previously generated icons if they exist
 * @returns {Object<string, string>}
 */
function loadExistingIcons() {
  const outputPath = join(__dirname, '../src/lib/generated-icons.js');
  if (!existsSync(outputPath)) {
    return {};
  }

  try {
    const content = readFileSync(outputPath, 'utf-8');
    const match = content.match(
      /export const preGeneratedIcons = ({[\s\S]*});/,
    );
    if (match) {
      return JSON.parse(match[1]);
    }
  } catch (err) {
    console.warn('Could not load existing icons, regenerating all');
  }

  return {};
}

async function generateIcons() {
  console.log('Generating icon SVGs...\n');

  const existingIcons = loadExistingIcons();
  const newIcons = {};
  let generatedCount = 0;
  let reusedCount = 0;

  // Generate or reuse each icon
  for (const [name, { collection, id }] of Object.entries(iconMap)) {
    const existingSvg = existingIcons[name];

    // For now, always regenerate to ensure up-to-date icons
    // In the future, we could check if collection version changed
    const svg = loadIconSvg(collection, id);

    if (svg) {
      newIcons[name] = svg;
      if (existingSvg && existingSvg === svg) {
        console.log(`→ Reused icon for ${name}`);
        reusedCount++;
      } else {
        console.log(`✓ Generated icon for ${name}`);
        generatedCount++;
      }
    } else {
      console.error(`✗ Failed to generate icon for ${name}`);
      if (existingSvg) {
        // Fallback to existing icon if generation fails
        newIcons[name] = existingSvg;
        console.log(`  → Using cached icon for ${name}`);
        reusedCount++;
      }
    }
  }

  // Write to file
  const outputPath = join(__dirname, '../src/lib/generated-icons.js');
  const content = `// This file is auto-generated by scripts/generate-icons.mjs
// Do not edit manually

export const preGeneratedIcons = ${JSON.stringify(newIcons, null, 2)};
`;

  writeFileSync(outputPath, content, 'utf-8');
  console.log(
    `\n✓ Icons written to ${outputPath} (${generatedCount} generated, ${reusedCount} reused)`,
  );
}

generateIcons().catch((err) => {
  console.error('Error generating icons:', err);
  process.exit(1);
});
